### ISSUE TITLE
[Feature Suggestion] Allow hit dice left to show as a resource

### ISSUE THREAD

**Issue by GhostwheelX** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#1]
Might is be possible to have the number of remaining hit dice left (of all classes possessed) show up as a resource, out of their respective maximum for the D&D 5e system?

**Comment by akrigline** [comment]
Thanks for this feedback, but this is beyond the scope of this module, which aims to be a very simple exercise in using already-consumable item charges as Resources. Adding hit dice to the mix would be a considerable amount of complexity for very little gain.

The core sheet (and all the other sheets I know of) display this natively, don't they?

**Comment by GhostwheelX** [comment]
> The core sheet (and all the other sheets I know of) display this natively, don't they?

Sure, but I use this module mostly to show class resources on the token, and for people who didn't have a primary one, I thought it would be nice to default to showing total hit dice. However, I understand if that's not possible, thanks anyhow.
