### ISSUE TITLE
Garcon, there's a "debugger" line in my code

### ISSUE THREAD

**Issue by wickermoon** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#10]
There are two "debugger;" calls in the code, which I'm pretty certain do not belong there.

They trigger when I close a character sheet AND the console (F12) is open.

**Comment by akrigline** [comment]
Whoops, forgot to take those out when I pushed the update last night. Good catch!

**Comment by wickermoon** [comment]
No biggie. I already fixed it. :)
