### ISSUE TITLE
Changing resource quantity does not save/does not update item quantity. 

### ISSUE THREAD

**Issue by Blake-Howard** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#13]
Foundry V10.285
LibWrapper 1.12.9
Link Item and Resource 1.2.2

When attempting to change the resource quantity it will revert back to item quantity on load, and does not adjust item quantity.

**Comment by akrigline** [comment]
Thanks for the detailed report!

Try Link Item and Resource v2.0.0+ on foundry core v10

**Comment by Blake-Howard** [comment]
Ah yup, that'll do it! Guess updated didn't bring me to v2.0.0. Thanks for swift response!
