### ISSUE TITLE
Update to V10?

### ISSUE THREAD

**Issue by galaara98** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#14]
Currently the module throws a bunch of warnings into the console because of changes to underlying structures in v10

Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.

**Comment by akrigline** [comment]
V2.0.0 of this module is v10 ready

**Comment by galaara98** [comment]
Ah, when I upgraded from v9, it would not update the module.  When I deleted it and readded it worked
