### ISSUE TITLE
Can't change resource total number value

### ISSUE THREAD

**Issue by stickas** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#18]
I have a cleric in DnD 5e System that I need to change his primary resource from 1 to 2 due to leveling.  I found that this mod is what is preventing me from doing so. Sheet is editable, I can change the current number value. I tried unlinking the features from the resources and I also tried disabling other mods but this is the only one that's preventing the change (only in that specific resource btw). Is there something that I'm missing or is this a bug?

**Comment by MrPrimate** [comment]
I think this is probably "working as intended" - it links the resource to the ability, so if you want to change the max of the resource, you adjust the ability it's linked to.
