### ISSUE TITLE
[Feature request] Make link work backwards too

### ISSUE THREAD

**Issue by SLinxTheFox** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#5]
Ex: I have a wand with 5 charges, if i want to refund some of the charges through the resource rather than through the item, I'd like for that to be possible

**Comment by akrigline** [comment]
Sorry, I'm not really sure what you're asking for compared to how the module currently works.

It definitely is supposed to be possible to use the resource inputs on the actor sheet to manipulate the charges on a linked item.

Can you maybe record a video or illustrate some screenshots of what you mean?

**Comment by akrigline** [comment]
I'm gonna close this as I am fairly certain the feature you're requesting is already in the module. Feel free to comment or repoen if that's not the case.
