### ISSUE TITLE
Wrapper for 'CONFIG.Actor.documentClass.prototype.update' did not chain the call to the next wrapper

### ISSUE THREAD

**Issue by Zamrod** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#6]
I received the following error:
== Technical Details:
Detected by libWrapper.
Package ID= link-item-resource-5e
Error= The wrapper for 'CONFIG.Actor.documentClass.prototype.update' registered by module link-item-resource-5e with type WRAPPER did not chain the call to the next wrapper, which breaks a libWrapper API requirement. This wrapper will be unregistered.

**Comment by akrigline** [comment]
https://github.com/ElfFriend-DnD/foundryvtt-link-item-resource-5e/blob/main/scripts/module.js#L206

**Comment by akrigline** [comment]
Fixed in 1.2.1
