### ISSUE TITLE
Corrupting Actor.db file

### ISSUE THREAD

**Issue by Mushie1** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#7]
Just letting you know that when I install and use this module, the Actor db file becomes filled with the same actor.
I adjusted 3 Feature resources on 2 actors and both actors had the same thing happen. 
![image](https://user-images.githubusercontent.com/77275833/145338167-692cdbd8-d077-4cda-b7d3-f1143e235eaf.png)
(it went from 3MB to 9MB)
I am using the Forge.  
5e version 1.5.3, 
Foundry 0.8.9
Character sheet used is Tidy5e.

**Comment by akrigline** [comment]
Are any other modules installed? Thanks for this report, I'll take a look as soon as I can.

**Comment by Mushie1** [comment]
wow that was quick, No hurry, just thought you would want to know.
Yeh - I have a bunch of modules active - probably around 45.  I'll get you a list if that helps.
I can try again on a world with no modules apart from tidy and this one to check. (wont be able to do that until a bit later)

**Comment by akrigline** [comment]
A module list would be good yeah just in case it's a conflict.

When this happens, what exactly is the user doing? Opening the actor sheet and modifying the overriden resource?

**Comment by Mushie1** [comment]
It was me as DM, opening the 2 actor sheets, and then going to the Features and changing the resource override to Resource 1 etc.

After it happened, I uninstalled the module, replaced with a backup and repeated the process, just incase it was me or something else, and the same thing happened.

It will be a few hours before I can get you the module list and I'll try with the same world with no modules at the same time.

**Comment by Mushie1** [comment]
So with no modules, the actor.db file went from 859k to 1281k,  not as bad compared to the original.
This is the actor.db before adding Linked item module
![no modules](https://user-images.githubusercontent.com/77275833/145396333-98e8d8cc-61a4-4c34-b821-d583676fe1d4.png)

This is the actor.db after - you can see the 2 actors copied at the bottom (Georgella & Harry)
![no modules after adding module](https://user-images.githubusercontent.com/77275833/145396468-666741ea-69cd-4967-8b35-6e9ef7e03348.png)

(Although interesting when I did this again, there were an extra couple of copies of them at the bottom)

Module List active when I did the original install.  I have put a *next to the ones that I think alter Actor sheets.

Let me know if I can help with more information.

Active Modules:
----------
1001 Fish v1.1.0;
Advanced Macros v1.12;
Ambient Doors v2.2.5;
Atropos' Patreon Battlemaps Pack v1.3.0;
*Automated Animations v0.6.65;
*Character Actions List dnd5e v4.3.0;
Characters (Shared Compendiums) vv1.0;
Collapsible Journal Sections v1.3.1;
Combat Utility Belt v1.7.3;
Compendium Folders v2.3.63;
Custom Token Animations v0.2.51;
Dice So Nice! v4.2.2;
Filepicker + v0.9;
Initiative Double Click v1.2;
*Item Containers v1.8.14;
JB2A - Patreon Complete Collection v0.3.1;
Keybind Lib v0.3.4;
Less Fog v0.8.6;
lib - Color Settings v2.8.1;
Library: Scene Packer v2.3.23;
libWrapper v1.11.0.0;
Lichtgeschwindigkeit (Lightspeed) v1.4.9;
Limithron's Oceans Islands and Ships v1.0.3;
*Loot Sheet NPC 5e v3.2.4;
*Magic Items v2.1.2;
Math.js v7.5.1-fvtt2;
Minimal UI v1.1.8;
*Monster Blocks v3.2.1;
Multilevel Tokens v1.5.2;
Multiple Wall Point Mover (MWPM) v0.5.0;
Parallaxia v0.3.6;
Permission Viewer v0.8.14;
Pings v1.2.12+0.8.6;
*PopOut! v2.4;
Quick Insert - Search Widget v2.5.0;
Sequencer v1.3.5;
Settings Extender v1.1.6+0.8.6;
socketlib v1.0.9;
Tabletop RPG Music v1.4.0;
*Tidy5e Sheet v0.5.19;
Tidy UI - Game Settings v0.1.28;
Tile Sort v0.6;
Token Z v0.6.1;
Wall Height v3.6.0.0;
Warp Gate v1.10.1;

**Comment by akrigline** [comment]
How are you keeping tabs on the db file and determining that it's corrupted?

I've looked around and asked around, by my understanding this is kind of how nedb works. As updates happen the rows in the database file aren't changed real-time but duplicated with the new data at the bottom. The server then compacts these database files at certain points (startup for sure, though I'm not certain how Forge hosting interacts with this process).

This compaction can take a while and generally happens in the background unnoticed so I'm hoping this isn't a problem with link-item-resource but instead a symptom of nedb processing your actor updates?

If you're willing, I'm curious to hear what happens if you reproduce this, then do the following:
1. Stop the game server
2. Wait a minute then start the game server again, join the game
3. Wait a few minutes, then export your game data and take a look.

I tried this with one of my games and the number of duplicates dropped drastically.

![Screen Shot 2021-12-09 at 10 55 46 AM](https://user-images.githubusercontent.com/7644614/145430302-6167b1c8-58ea-40d7-b471-ca9b42b79254.png)

**Comment by Mushie1** [comment]
Thanks for the reply. To check .db file from the Forge, I export the world to my PC, unzip the file, and open up the .db file in an editor.   Admittedly I did check reasonably quickly after using your module.
 
I am more then happy to try a again a little later today.  Thanks for looking into this - I hope I havent caused a false alarm.

**Comment by Mushie1** [comment]
Hi akrigline,  so I finally had some time to test this.  So initially it did bloat my test world, but after stopping, waiting a few minutes and **then** restarting the server the file size dropped back down again.
I am very sorry to have brought this up.   
Thank you for your patience.

**Comment by akrigline** [comment]
Gotchya, thanks for circling back. You had good instincts, nedb is just weird about this and the forge abstracts away some of the normal compaction techniques
