### ISSUE TITLE
Spell Slots as a Resource?

### ISSUE THREAD

**Issue by bklick** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#9]
Hi! Is there a way to have a resource connect to a spell slot?

**Comment by akrigline** [comment]
I believe you're asking from the perspective of item consumption consuming a spell slot as resource.

This module doesn't mess with the consumption logic, only the display of item charges as actor resources on the sheet.

I want to say the core system allows targeting spell slots with consumption, but only if you target a specific level of spell slot.

Either way, closing this as not within the scope of this module.

**Comment by bklick** [comment]
I think I communicated my request poorly (you are talking over my head though, and I am genuinely not sure what a lot of what you were saying meant), so I want to share a screenshot that maybe expresses my thought better.

![image](https://user-images.githubusercontent.com/3947702/178188619-57ea2ffa-9665-46aa-9256-ec6754630530.png)

IE, if the player casts any first level spell, the number would decrease. It is definitely not a core feature, at least I don't think so. x_x

Thanks again, sorry for not understanding. 

If I could make an item that simply counts spell slots, and then have this module put that item in a resource position, that would do the trick. I'm not sure how to do that, though.

Thanks for your time!
